//
//  RegisterModels.swift
//  clean swift experiments
//
//  Created by Kanaan Zafar on 20/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Register
{
    // MARK: Use cases
    
    enum SignUp
    {
        struct Request
        {
            let username,email,  password: String
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
        struct ViewModelSuccess{
            let name: String
        }
        struct ViewModelError{
            let error: Error
        }
    }
}
