//
//  RegisterPresenter.swift
//  clean swift experiments
//
//  Created by Kanaan Zafar on 20/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPresentationLogic
{
    func presentRegistrationComplete(_: String?, _: Error?) -> Void
}

class RegisterPresenter: RegisterPresentationLogic
{
    func presentRegistrationComplete(_ name: String?, _ error: Error?) {
        if let errorProduced = error {
            let viewModelFailure = Register.SignUp.ViewModelError(error: errorProduced)
            viewController?.failedToRegister(viewModelError: viewModelFailure)
        }else {
            let viewModelSuccess = Register.SignUp.ViewModelSuccess(name: name!)
            viewController?.successfullyRegistered(viewModelSuccess: viewModelSuccess)
        }
    }
    
    
    
    weak var viewController: RegisterDisplayLogic?
    
}
