//
//  RegisterRouter.swift
//  clean swift experiments
//
//  Created by Kanaan Zafar on 20/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
        func fetchEmail() -> String
    func routeToHome(segue: UIStoryboardSegue?, name: String)
    
}

protocol RegisterDataPassing
{
    var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing
{
    func fetchEmail() -> String {
        let email = dataStore?.email
        return email ?? ""
    }
    
    weak var viewController: RegisterViewController?
    var dataStore: RegisterDataStore?
    
    // MARK: Routing
    
    
    func routeToHome(segue: UIStoryboardSegue?, name: String)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! HomeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToHome(name: name, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Home", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: Constants.homeScreenId) as! HomeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToHome(name: name, destination: &destinationDS)
            navigateToHome(source: viewController!, destination: destinationVC)
        }
    }
    
    
    // MARK: Navigation
    func navigateToHome(source: RegisterViewController, destination: HomeViewController)
    {
        source.show(destination, sender: nil)
        // remove all previous VCs from stack, swift.
        //
    }
    
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: RegisterDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
    func passDataToHome(name : String, destination: inout HomeDataStore)
    {
        destination.name = name
    }
    
}
