//
//  TaskDetailsModels.swift
//  clean swift experiments
//
//  Created by Kanaan Zafar on 25/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TaskDetails
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    enum DeleteTask {
        struct Request {
            let taskId: String
        }
        struct Response {
            let error: Error?
        }
        struct TaskDeletedSuccessfully {}
        struct TaskDeletionFailed {
            let error: Error
        }
    }
    enum UpdateTask {
        struct Request {
            let task: Task
        }
        struct Response{
            let error: Error?
        }
        struct TaskUpdatedSuccessfully {}
        struct TaskUpdationFailed {
            let  error: Error
        }
    }
}
