//
//  LoginRouter.swift
//  clean swift experiments
//
//  Created by Kanaan Zafar on 20/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //    func navigateToRegister(source: LoginViewController, destination: RegisterViewController)
    //    func routeToRegisterScreen(email : String, source : LoginViewController)
    func routeToRegister(segue: UIStoryboardSegue?, email : String?)
    func routeToHome (segue: UIStoryboardSegue?, name: String)
}

protocol LoginDataPassing
{
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    
    
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeToHome(segue: UIStoryboardSegue?, name: String) {
        if let segueToHome = segue {
            let destinationVC = segueToHome.destination as! HomeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToHome(name: name, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Home", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: Constants.homeScreenId) as! HomeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToHome(name: name, destination: &destinationDS)
            navigateToHome(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToRegister(segue: UIStoryboardSegue?, email : String?)
    {
        dataStore?.email = email ?? ""
        if let segueToRegister = segue {
            print("-----segue notnoll")
            let destinationVC = segueToRegister.destination as! RegisterViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToRegister(source: dataStore!, destination: &destinationDS)
            viewController?.performSegue(withIdentifier: segueToRegister.identifier!, sender: nil)
        } else {
            print("-----segue null")
            let storyboard = UIStoryboard(name: "Register", bundle: nil)
            //            let storyboard = UIStoryboard(name: Constants.loginScreenId, bundle: nil)
            
            let destinationVC = storyboard.instantiateViewController(withIdentifier: Constants.registerScreenId) as! RegisterViewController
            var destinationDS = destinationVC.router!.dataStore!
            //        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            passDataToRegister(source: dataStore!, destination: &destinationDS)
            //        navigateToSomewhere(source: viewController!, destination: destinationVC)
            navigateToRegister(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: LoginViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    //MARK: Navigation to register
    func navigateToRegister(source: LoginViewController, destination: RegisterViewController) {
        
        //        print("-----navigate to register called")
        source.show(destination, sender: nil)
    }
    func navigateToHome(source: LoginViewController, destination: HomeViewController) {
        //     source.show(destination, sender: nil)
        //        let storyboard = UIStoryboard(name: "Home", bundle: nil)
        //        let initialViewController = storyboard.instantiateViewController(withIdentifier: initialViewControllerId)
        /* let navControl = UINavigationController(rootViewController: destination)
         let window = UIWindow(windowScene: <#T##UIWindowScene#>)
         self.window = UIWindow(windowScene: scene as! UIWindowScene)
         self.window?.rootViewController = navControl
         self.window?.makeKeyAndVisible()
         */
        
        //working:
        
         source.show(destination, sender: nil)
         guard let navigationController = viewController?.navigationController else { return }
         var navigationArray = navigationController.viewControllers // To get all UIViewController stack as Array
         navigationArray.removeAll() // To remove previous UIViewController
         viewController?.navigationController?.viewControllers = [destination]
         
        
//        let navControl = UINavigationController(rootViewController: destination)
//        let mySceneDelegate = self.view.window.roo

        
        
    }
    // MARK: Passing data
    func passDataToRegister(source: LoginDataStore, destination: inout RegisterDataStore){
        
        destination.email = source.email
        print("++++++passDataToRegisterCalled \(destination.email) and \(source.email)")
        
    }
    func passDataToHome(name: String, destination: inout HomeDataStore) {
        destination.name = name
        
    }
    
    
    /* func routeToRegisterScreen(email : String, source : LoginViewController) {
     let registerViewController = RegisterViewController()
     registerViewController.modalPresentationStyle = .fullScreen
     source.show(registerViewController, sender: source)
     //        navVC.pushViewController(registerViewController, animated: true)
     
     //    if let navVC = viewController?.navigationController {
     //              let detailVC = PhotoDetailViewController(photoID: photoID)
     
     //          }
     } */
}
