//
//  AddTaskSceneModels.swift
//  clean swift experiments
//
//  Created by Kanaan Zafar on 24/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddTaskScene
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    enum TaskUpload {
        struct Request {
            let title : String
            let description : String
            let notificationTime : Date
        }
        struct Response {
            let task : Task?
            let error : Error?
        }
        struct TaskUploadSuccessModel {
            let task : Task
        }
        struct  TaskUploadFailedModel {
            let error : Error
        }
    }
}
