//
//  AddTaskSceneRouter.swift
//  clean swift experiments
//
//  Created by Kanaan Zafar on 24/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddTaskSceneRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeBackToHomeScreen()
}

protocol AddTaskSceneDataPassing
{
  var dataStore: AddTaskSceneDataStore? { get }
}

class AddTaskSceneRouter: NSObject, AddTaskSceneRoutingLogic, AddTaskSceneDataPassing
{
    
  weak var viewController: AddTaskSceneViewController?
  var dataStore: AddTaskSceneDataStore?
  
  // MARK: Routing
    func routeBackToHomeScreen() {
        viewController?.navigationController?.popViewController(animated: true)
  }

  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: AddTaskSceneViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: AddTaskSceneDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
