//
//  AddTaskSceneInteractor.swift
//  clean swift experiments
//
//  Created by Kanaan Zafar on 24/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddTaskSceneBusinessLogic
{
    func doSomething(request: AddTaskScene.Something.Request)
    func addTask(title : String, description : String, dateTime : Date)
}

protocol AddTaskSceneDataStore
{
    //var name: String { get set }
}

class AddTaskSceneInteractor: AddTaskSceneBusinessLogic, AddTaskSceneDataStore
{
    //MARK: - Add Task
    func addTask(title : String, description : String, dateTime : Date) {
        let request = AddTaskScene.TaskUpload.Request(title: title, description: description, notificationTime: dateTime)
        worker = AddTaskSceneWorker()
        worker?.uploadTask(request: request, completion: { task, error in
            let response = AddTaskScene.TaskUpload.Response(task: task, error: error)
            self.presenter?.uploadTaskComplete(response: response)
        })
        
    }
    
    var presenter: AddTaskScenePresentationLogic?
    var worker: AddTaskSceneWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: AddTaskScene.Something.Request)
    {
        worker = AddTaskSceneWorker()
        worker?.doSomeWork()
        
        let response = AddTaskScene.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
