//
//  AddTaskScenePresenter.swift
//  clean swift experiments
//
//  Created by Kanaan Zafar on 24/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddTaskScenePresentationLogic
{
    func presentSomething(response: AddTaskScene.Something.Response)
    func uploadTaskComplete(response: AddTaskScene.TaskUpload.Response)
}

class AddTaskScenePresenter: AddTaskScenePresentationLogic
{
    
    weak var viewController: AddTaskSceneDisplayLogic?
    
    
    func presentSomething(response: AddTaskScene.Something.Response)
    {
        let viewModel = AddTaskScene.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    func uploadTaskComplete(response: AddTaskScene.TaskUpload.Response) {
        if let uploadError = response.error {
            //            viewController
            let failureViewModel = AddTaskScene.TaskUpload.TaskUploadFailedModel(error: uploadError)
            viewController?.taskUploadFailed(failureViewModel: failureViewModel)
        } else {
            let successViewModel = AddTaskScene.TaskUpload.TaskUploadSuccessModel(task: response.task!)
            viewController?.taskUploadedSuccessfully(successViewModel: successViewModel)
        }
    }
    
}
